{% set name = "libcsm" %}
{% set version = "3.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/USGS-Astrogeology/csm

build:
  number: 1

#requirements:
#  build:
#    - vc 10  # [win]


test:
  commands:
    - test -e $PREFIX/lib/libcsmapi.so  # [linux]
    - test -e $PREFIX/lib/libcsmapi.dylib  # [osx]
    - test -e $PREFIX/include/csm/Isd.h  # [not win]
    - test -e $PREFIX/include/csm/csm.h  # [not win]

about:
  home: https://github.com/USGS-Astrogeology/csm
  license: None
  summary: "This is the Community Sensor Model base interface library."

extra:
  recipe-maintainers:
    - jlaura
