{% set name = "libcsm" %}
{% set version = "3.0.1" %}
{% set sha256 = "eab1814242549a1fceb1815e3c1cacda531efeeb7a0cfe79382eb45cc0ce1e8c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/USGS-Astrogeology/csm

build:
  number: 1
  script_env: 
    - VERSION
    - CONDA_BLD_PATH

#requirements:
#  build:
#    - vc 10  # [win]


test:
  commands:
    - test -e $PREFIX/lib/libcsmapi.so  # [linux]
    - test -e $PREFIX/lib/libcsmapi.dylib  # [osx]
    - test -e $PREFIX/include/csm/Isd.h  # [not win]
    - test -e $PREFIX/include/csm/csm.h  # [not win]

about:
  home: https://github.com/USGS-Astrogeology/csm
  license: None
  summary: "This is the Community Sensor Model base interface library."

extra:
  recipe-maintainers:
    - jlaura
