# Build worker image (VM template)
image: Visual Studio 2015

branches:
  only:
  - master

version: '3.0.1'

platform:
  - x86

configuration:
  - Release

build: off

install:
  - ps: C:/Miniconda/bin/conda config --set always_yes yes --set changeps1 no
  - ps: C:/Miniconda/bin/conda update -q conda

on_success:
  - ps: C:/Miniconda/bin/conda install conda-build anaconda-client
  - ps: conda config --set anaconda_upload yes
  - ps: C:/miniconda/bin/conda build --token $CONDA_UPLOAD_TOKEN .

test_script:
  - conda build recipes
