# Build worker image (VM template)
image: Visual Studio 2015

branches:
  only:
  - master

version: '3.0.1.{build}'

platform:
  - x86

configuration:
  - Release

install:
  - cmd: call C:\\Miniconda36-x64\Scripts\activate.bat
  - cmd: conda config --set always_yes yes --set changeps1 no
  - cmd: conda update -q conda
  - cmd: conda install conda-build anaconda-client
  - cmd: conda config --set anaconda_upload yes

on_success:
  - cmd: conda build --token $CONDA_UPLOAD_TOKEN .

build: off

test_script:
  - conda build recipes
